version: "3"

services:
  mysql:
    image: mysql:5.7
    expose:
    - '3306'
    ports:
    - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=cms
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=cms_v1
  redis:
    image: redis
    expose:
    - '6379'
    ports:
    - '6379:6379'
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672