server:
  port: 8882
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  zipkin:
    baseUrl: http://localhost:8889/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 0.0