server:
  port: 8881
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  zipkin:
    baseUrl: http://localhost:8889/
    sender:
      type: web
  sleuth:
    sampler:
      percentage: 0.0